name: 'Get Latest Tag'
description: 'Get the latest tag from git and outputs that for use in other actions'
branding:
  icon: 'clock'
  color: 'orange'
outputs:
  tag:
    description: 'Latest tag'
    type: string
    required: true
runs:
  using: 'node12'
  main: 'main.js'
